name: Check for duplicate .puml filenames

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "docs/plantuml/**"

jobs:
  check_duplicates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Find duplicate .puml files
        id: find_duplicates
        run: |
          # Tìm tất cả file .puml trong thư mục docs và các thư mục con
          files=$(find docs -type f -name '*.puml' | sed 's|.*/||' | sort)
          duplicates=$(echo "$files" | uniq -d)

          # Kiểm tra nếu có file trùng tên
          if [ -n "$duplicates" ]; then
            echo "Duplicate .puml files found:"
            echo "$duplicates"
            echo "::set-output name=has_duplicates::true"
            echo "::set-output name=duplicates::$duplicates"
          else
            echo "No duplicate .puml files found."
            echo "::set-output name=has_duplicates::false"
          fi

      - name: Comment on Pull Request
        if: steps.find_duplicates.outputs.has_duplicates == 'true'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          script: |
            const duplicates = '${{ steps.find_duplicates.outputs.duplicates }}';
            const message = `🚨 **Duplicate .puml filenames found!** 🚨\n\nThe following files have duplicate names:\n\`\`\`\n${duplicates}\n\`\`\`\nPlease rename them to avoid conflicts.`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });
