name: Convert PlantUML to Image

on:
  push:
    paths:
      - "src/docs/uml/**" # Kích hoạt khi có thay đổi trong thư mục uml

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@master
        with:
          path: example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
