name: Sync Wiki

on:
  gollum:
  push:
    paths:
      - 'docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync to Wiki
        uses: kawamataryo/github-wiki-sync-actions@v0.0.3
        with:
          token: ${{ secrets.MY_TOKEN }}
